# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=150)),
                ('a', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
