# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botinterface', '0002_auto_20170326_0852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='qa',
            new_name='Question',
        ),
    ]
